export default function AboutPage() {
  return (
    <article className="max-w-4xl space-y-8">
      <header><p className="text-xs font-mono uppercase tracking-wider text-[var(--bp-cyan)]">About Corkscrew</p><h1 className="font-display text-3xl sm:text-4xl mt-2">Making Quantum Computing Accessible to Everyone</h1><p className="mt-4 text-sm leading-7 text-[var(--bp-text-dim)]">Quantum computing is shaping the future of technology, but getting started can feel overwhelming. Corkscrew was created to change that.</p><p className="mt-3 text-sm leading-7 text-[var(--bp-text-dim)]">We are a team passionate about making quantum computing easier to understand, explore, and learn. Our goal is to reach students, self-learners, and quantum computing enthusiasts, helping them take their first steps into this fascinating field—regardless of their background or prior experience.</p></header>
      <section className="bp-panel p-6"><h2 className="font-display text-2xl">Our Mission</h2><p className="mt-3 text-sm leading-7 text-[var(--bp-text-dim)]">We believe that learning quantum computing should be accessible, interactive, and engaging. Corkscrew brings together structured learning modules, hands-on quantum circuit exploration, and assessments to help learners build a strong foundation in quantum concepts.</p><p className="mt-3 text-sm leading-7 text-[var(--bp-text-dim)]">Whether you're a student curious about qubits, a self-learner exploring quantum algorithms, or someone taking their first step toward a career in quantum technology, Corkscrew is designed to help you learn at your own pace and turn curiosity into understanding.</p></section>
      <section className="bp-panel p-6"><h2 className="font-display text-2xl">Supporting India's Quantum Vision</h2><p className="mt-3 text-sm leading-7 text-[var(--bp-text-dim)]">India is investing in its future through the <strong>National Quantum Mission (NQM)</strong>, approved by the Government of India in 2023 to strengthen research, innovation, and skilled human resources in quantum technologies.</p><p className="mt-3 text-sm leading-7 text-[var(--bp-text-dim)]">Corkscrew aligns with this vision by focusing on learning and skill development. By making quantum concepts approachable and encouraging more learners to explore the field, we hope to contribute to a stronger and more inclusive quantum workforce in India.</p></section>
      <section className="bp-panel p-6"><h2 className="font-display text-2xl">About the National Quantum Mission</h2><p className="mt-3 text-sm leading-7 text-[var(--bp-text-dim)]">The National Quantum Mission is an eight-year initiative, approved with an outlay of ₹6,003.65 crore for 2023–24 to 2030–31. Its goal is to advance India's capabilities in quantum computing, quantum communication, quantum sensing and metrology, and quantum materials and devices.</p><p className="mt-3 text-sm leading-7 text-[var(--bp-text-dim)]">The mission also aims to develop skilled human resources, foster innovation, and strengthen India's position in quantum technology. Corkscrew shares this broader vision of building a future where more people have the knowledge and confidence to participate in the quantum revolution.</p></section>
      <footer className="border-l-2 border-[var(--bp-cyan)] pl-5"><h2 className="font-display text-2xl">Learn. Explore. Innovate.</h2><p className="mt-3 text-sm leading-7 text-[var(--bp-text-dim)]">We are Corkscrew—a team building a starting point for the next generation of quantum explorers.</p><p className="mt-2 text-sm leading-7 text-[var(--bp-text-dim)]">Because the future of quantum computing should not belong to a few. It should be open to everyone willing to learn.</p></footer>
    </article>
  );
}
